### ISSUE TITLE
Add non-Passport.js version

### ISSUE THREAD

**Issue by CloutProject** [hoangvvo/nextjs-mongodb-app#42]
Go on the login and enter a unexistant email/password. The page loads and the website crashes. The problem seemed to be coming from passport, but I'm not sure.

Also, could you release a version with all the recent modifications, but without passport?

Great job on the project by the way, it's awesome!

**Comment by hoangvvo** [comment]
I'm closing this issue since I am not intending to maintain a parallel non-passport.js version. Still, you can always look at this post: https://dev.to/hoangvvo/how-i-build-a-full-fledged-app-with-next-js-and-mongodb-part-1-user-authentication-3io9 

The client-side logic would be the same. The only difference is the API.
