### ISSUE TITLE
the option [***] is not supported + Deprication warnings

### ISSUE THREAD

**Issue by StarAzure** [hoangvvo/nextjs-mongodb-app#87]
Warnings firing 
the option [***] is not supported + Deprication warnings
![image](https://user-images.githubusercontent.com/12852059/88446994-c04dd380-cdfc-11ea-8a9a-5b5fb1716018.png)

**To Reproduce**
Look at cmd after compile

**Expected behavior**
Deprication warnings should not appear. 

**Desktop (please complete the following information):**
 - OS: Win 10 with Mongo Compass Community 1.21.2 (latest stable version)
 - Browser - Chrome/ Firefox

**Additional context**
I do not see more than one connections. Client.Connect is only in middleware and bable cache

**Comment by hoangvvo** [comment]
The error happens because we tries to `client.connect` many times (especially in dev environment with hot reload): https://jira.mongodb.org/browse/NODE-1868

However, in our code, we have already checked against it with `client.isConnected()` so that `client.connect` is called only once.

https://github.com/hoangvvo/nextjs-mongodb-app/blob/master/middlewares/database.js#L17

...which, however, does not work with `useUnifiedTopology: true` @.@

https://jira.mongodb.org/browse/NODE-2234

**Comment by StarAzure** [comment]
@hoangvvo Based on your response
1) These errors can be safely ignored because they will go away in Prod
2) If I really want these to go away, I should set `useUnifiedTopology: false` but remember to set it back to true in Prod
